### ISSUE TITLE
报错，运行不起来

### ISSUE THREAD

**Issue by uu993** [Nightonke/Saver#20]
Process: com.nightonke.cocoin, PID: 26776
                                                                      android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@7aade33 -- permission denied for this window type
                                                                          at android.view.ViewRootImpl.setView(ViewRootImpl.java:598)
                                                                          at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:276)
                                                                          at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                                          at com.github.johnpersano.supertoasts.ManagerSuperToast.displaySuperToast(ManagerSuperToast.java:189)
                                                                          at com.github.johnpersano.supertoasts.ManagerSuperToast.handleMessage(ManagerSuperToast.java:146)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5238)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

**Comment by dongxue0223** [comment]
java.lang.RuntimeException: Couldn't dump heap; open("/storage/emulated/0/Download/leakcanary/suspected_leak_heapdump.hprof") failed: No such file or directory
